Config =  {}

Config.Locale = 'en'
Config.Currency = '$'

Config.DrawMarker = {type = 23, r = 255, g = 255, b = 255, opacity = 80, size = 0.8}

Config.MenuPosition = {X = 0, Y = 0}
Config.MenuWidthOffset = -50

Config.OpenMenu = 'f2'
Config.HandsUp = 'h'

Config.HandcuffItem = 'ropes'   -- set nil if you don't want an item to be needed
Config.HeadbagItem = 'headbag'

Config.DisableSprintWhenCarrying = false

Config.RobberyMenu = {
    playermenuV2 = true,    -- integrated robbery menu
    ox_inventory = false
}

Config.MenuContent = {
    playerInteraction = true,
    vehicleInteraction = true,
    clothing = true,
    inventory = true,
    billing = true,
    animation = true,   -- requires dp_emotes
    waypoint = true,
    gps = true,
    information = true
}

Config.PlayerInteractions = {
    carry = true,
    handcuff = true,
    escort = true,
    search = true,
    putInVehicle = true,
    takeFromVehicle = true,
    takeOffMask = true,
    headbag = true,
    licenses = true,
    job = true,
    inviteJob = true,
    fire = true,
    promote = true,
    degrade = true
}

Config.UnemployedJob = 'unemployed'

-- Ranks that are authorized to hire, fire, promote and degrade players
Config.JobBossAccess = {
    'boss',
    'chief',
    'lieutenant',
    'chief_doctor'
}

-- Config.MenuContent.inventory must be set to true for this
Config.Inventory = {
    playermenuV2 = true,    -- integrated inventory
    ox_inventory = false,
}

Config.Billing = {
    default = true,
    myBilling = false,
}

-- Job Restricted GPS Channels
Config.JobRestrictedChannels = {
    [911] = {'police', 'fbi'},
    [912] = {'ambulance'},
    [913] = {'mechanic'},
}

Config.GPSItem = 'gps'      -- set nil if you don't want an item to be needed
Config.RefreshRate = 1500   -- default: 2 seconds
Config.GPSBlip = {
    id = 128,
    color = 38,
    size = 0.8
}

Config.Waypoints = {
    {label = 'Police Department', x = 430.1171, y = -982.0900},
    {label = 'Medical Department', x = 298.2839, y = -584.4869},
    {label = 'Remove Waypoint'}
}


Config.AutopilotKey = 'f10'
Config.AutopilotDriveStyle = 262207     -- calculator: https://vespura.com/fivem/drivingstyle/
Config.AutopilotDriveSpeed = 35.0
Config.AutopilotForEveryVehicle = true
Config.AutopilotVehicleList = {
    -- this list is only considered if Config.AutopilotForEveryVehicle is set to false
    'BANSHEE',
    'ADDER',
}

Config.CruiseControlKey = 'z'

Config.JsfourIDCard = true
Config.CustomIDCard = false

function openTargetIDCard(target, me)
    -- insert your event here

end

function showMyLicense(me, target, license)
    -- insert your event here

end

Translation = {
    ['de'] = {
        ['handsup_error'] = '~r~Du kannst nicht die Hände heben, wenn du der Fahrer bist.',
        ['robmenu_title'] = 'Durchsuchen',
        ['robmenu_subtitle'] = 'Person durchsuchen',
        ['robmenu_idcard'] = 'Ausweis ansehen',
        ['robmenu_idcard_notify'] = 'Ausweis ansehen..',
        ['amount'] = 'Anzahl',
        ['amount_desc'] = 'Gebe eine Anzahl ein.',
        ['ammo'] = ' Schuss',
        ['playeractions_title'] = 'Interaktionen',
        ['playeractions_subtitle'] = 'Wähle ein Spieler aus',
        ['license_idcard'] = 'Ausweis',
        ['license_driver'] = 'Führerschein',
        ['license_gun'] = 'Waffenschein',
        ['player_nearby'] = 'Spieler',
        ['carry'] = 'Person tragen',
        ['noplayers_nearby'] = 'Kein Spieler in der Nähe!',
        ['handcuff'] = 'Seile',
        ['handcuff_apply'] = 'Anlegen',
        ['handcuff_release'] = 'Lösen',
        ['search'] = 'Durchsuchen',
        ['search_error'] = '~r~Die Person muss die Hände heben oder gefesselt sein!',
        ['putInVehicle'] = 'Person in Fahrzeug setzen',
        ['putInVehicle_error'] = '~r~Die Person muss gefesselt sein!',
        ['takeFromVehicle'] = 'Person aus Fahrzeug nehmen',
        ['licenses'] = 'Lizenzen geben',
        ['invitejob'] = 'In Fraktion einladen',
        ['invite_sent'] = 'Du hast eine ~g~Einladung ~s~verschickt!',
        ['idcard_showed'] = 'Du hast dein ~g~Ausweis ~s~gezeigt',
        ['driverslicense_showed'] = 'Du hast dein ~g~Führerschein ~s~gezeigt',
        ['gunlicense_showed'] = 'Du hast dein ~g~Waffenschein ~s~gezeigt',
        ['handcuff_error'] = '~r~Der Spieler muss die Hände heben, damit du ihn fesseln kannst!',
        ['no_handcuff_item'] = '~r~Du hast keine Seile!',
        ['player_cuffed'] = 'Du hast die Person ~g~entfesselt.',
        ['player_toofar'] = 'Die Person ist zu weit weg.',
        ['playermenu_title'] = 'Playermenu',
        ['playermenu_subtitle'] = 'Interaktionsmenü',
        ['playerinteractions'] = 'Spieler Interaktion',
        ['driver'] = 'Fahrer',
        ['passenger'] = 'Beifahrer',
        ['backleft'] = 'Hinten Links',
        ['backright'] = 'Hinten Rechts',
        ['trunk'] = 'Kofferraum',
        ['hood'] = 'Motorhaube',
        ['vehicleinteractions'] = 'Fahrzeug Interaktion',
        ['toggleengine'] = 'Motor',
        ['doors'] = 'Türen öffnen/schließen',
        ['windows'] = 'Fenster öffnen/schließen',
        ['engine_on'] = 'Motor ~g~gestartet!',
        ['engine_off'] = 'Motor ~r~gestoppt!',
        ['vehicle_toofar'] = '~r~Das Fahrzeug ist zu weit weg!',
        ['open'] = 'Öffnen',
        ['close'] = 'Schließen',
        ['vehicle_locked'] = 'Das Fahrzeug ist ~r~abgeschlossen!',
        ['vehicleinteraction_locked'] = '~t~Fahrzeug Interaktion',
        ['clothing'] = 'Kleidung',
        ['on'] = 'An',
        ['off'] = 'Aus',
        ['hat'] = 'Helm/Hut',
        ['mask'] = 'Maske',
        ['glasses'] = 'Brille',
        ['ears'] = 'Ohr Accessories',
        ['chain'] = 'Kette',
        ['bag'] = 'Rucksack',
        ['torso'] = 'Torso',
        ['tshirt'] = 'T-Shirt',
        ['pants'] = 'Hose',
        ['shoes'] = 'Schuhe',
        ['inventory'] = 'Inventar',
        ['bills'] = 'Rechnungen',
        ['closestatm'] = 'Nächster ATM',
        ['closestgasstation'] = 'Nächste Tankstelle',
        ['waypoint'] = 'Wegpunkt setzen',
        ['new_waypoint1'] = 'Wegpunkt auf ~g~',
        ['new_waypoint2'] = ' ~s~gesetzt!',
        ['waypoint_removed'] = 'Du hast den Wegpunkt ~r~entfernt.',
        ['gps'] = 'GPS Channel',
        ['gps_code'] = 'GPS-Code',
        ['gps_code_input'] = 'GPS-Code eingeben',
        ['gps_off'] = 'GPS deaktivieren',
        ['gps_off_notify'] = 'Du hast dein GPS ~r~deaktiviert!',
        ['no_gps_item'] = '~r~Du hast kein GPS-Gerät!',
        ['informations'] = 'Informationen',
        ['charname'] = 'Vor- & Nachname:',
        ['birthdate'] = 'Geburtsdatum:',
        ['job'] = 'Job:',
        ['salary'] = 'Gehalt:',
        ['playtime'] = 'Spielzeit:',
        ['channel_joined1'] = 'Du hast den GPS Kanal ~g~',
        ['channel_joined2'] = ' ~s~betreten!',
        ['animations_title'] = 'Animationen',
        ['animations_subtitle'] = 'Favorisierte Animationen',
        ['save_anim'] = '~g~Neue Animation speichern',
        ['manage_anims'] = 'Animationen verwalten',
        ['save_anim_input'] = 'Animation speichern',
        ['animlabel_input'] = 'Name:',
        ['animlabel_input_desc'] = 'Wie willst du die Animation nennen?',
        ['anim_input'] = 'Animation:',
        ['rename_anim'] = 'Umbenennen',
        ['delete_anim'] = '~r~Löschen',
        ['new_animlabel'] = 'Neuer Animationsname:',
        ['anim_desc'] = 'Animation: ~b~',
        ['inventory_title'] = 'Inventar',
        ['weight'] = 'Gewicht: ',
        ['use'] = 'Benutzen',
        ['give'] = 'Geben',
        ['drop'] = 'Wegwerfen',
        ['use_error'] = '~r~Du hast kein ',
        ['select_player'] = 'Wähle einen Spieler aus',
        ['give_request1'] = 'Jemand will dir ~g~',
        ['give_request2'] = ' ~s~geben. Drücke ~g~Z ~s~um es anzunehmen!',
        ['item_accepted1'] = 'Du hast ~g~',
        ['item_accepted2'] = ' ~s~angenommen!',
        ['weapon_accepted1'] = 'Du hast eine ~g~',
        ['weapon_accepted2'] = ' ~s~angenommen!',
        ['decline_item'] = 'Du hast den Gegenstand ~r~abgelehnt!',
        ['gasstation_waypoint'] = 'Wegpunkt auf die ~g~nächste Tankstelle ~s~gesetzt!',
        ['gasstation_error'] = '~r~Keine Tankstelle gefunden!',
        ['atm_waypoint'] = 'Wegpunkt auf den ~g~nächsten ATM ~s~gesetzt!',
        ['atm_error'] = '~r~Kein ATM gefunden!',
        ['putInVehicle_targetnotify'] = 'Du wurdest in das Fahrzeug ~r~gesetzt!',
        ['jobinvite_accepted'] = 'Du hast die Einladung ~g~angenommen!',
        ['jobinvite_declined'] = 'Du hast die Einladung ~r~abgelehnt!',
        ['jobinvite_expired'] = 'Die Einladung ist ~r~abgelaufen!',
        ['handcuff_applied'] = 'Du hast die Person ~g~gefesselt!',
        ['handcuff_released'] = 'Du wurdest ~g~freigelassen!',
        ['handcuff_applied_target'] = 'Du wurdest ~r~gefesselt!',
        ['anim_renamed'] = 'Du hast die Animation umbenannt zu "~b~',
        ['anim_deleted'] = 'Du hast die Animation ~r~gelöscht!',
        ['channel_restricted'] = '~r~Das ist ein geschützter GPS Kanal',
        ['anim_saved'] = 'Du hast eine neue Animation ~g~gespeichert!',
        ['target_searchidcard'] = 'Dein Ausweis wurde ~r~genommen!',
        ['target_nolonger_searching'] = 'Du wirst nicht mehr durchsucht.',
        ['target_robbed_item1'] = 'Dir wurde ~r~',
        ['target_robbed_item2'] = ' ~s~gestohlen!',
        ['robbed_item1'] = 'Du hast ~g~',
        ['robbed_item2'] = ' ~s~gestohlen!',
        ['cantcarry'] = '~r~Du kannst nicht so viel tragen.',
        ['target_robbed_gun1'] = 'Dir wurde eine ~r~',
        ['target_robbed_gun2'] = ' ~s~gestohlen!',
        ['robbed_gun1'] = 'Du hast eine ~g~',
        ['robbed_gun2'] = ' ~s~gestohlen!',
        ['hasweapon'] = '~r~Du hast diese Waffe bereits!',
        ['give_request_sent'] = 'Du hast eine Anfrage ~g~gesendet!',
        ['target_hasweapon'] = '~r~Die Person hat die Waffe bereits!',
        ['give_accepted'] = 'Dein Gegenstand wurde ~g~angenommen!',
        ['give_declined'] = 'Dein Gegenstand wurde ~r~abgelehnt!',
        ['target_search_notify'] = 'Du wirst gerade durchsucht..',
        ['target_jobinvite1'] = 'Du wurdest zu der Fraktion ~g~',
        ['target_jobinvite2'] = ' ~s~eingeladen. Drücke ~g~Z ~s~um es anzunehmen!',
        ['sender_jobinvite_accepted'] = 'Die Einladung wurde ~g~angenommen!',
        ['sender_jobinvite_declined'] = 'Die Einladung wurde ~r~abgelehnt!',
        ['jobfire'] = 'Aus Fraktion werfen',
        ['promote'] = 'Befördern',
        ['degrade'] = 'Degradieren',
        ['target_kicked'] = 'Du wurdest von deiner Fraktion ~r~gekündigt!',
        ['kicked'] = 'Du hast die Person ~r~gekündigt!',
        ['not_samejob'] = 'Die Person ist nicht in deiner Fraktion!',
        ['degraded1'] = 'Du hast die Person zu ~r~',
        ['degraded2'] = ' ~s~degradiert!',
        ['target_degraded1'] = 'Du wurdest zum Rang ~r~',
        ['target_degraded2'] = ' ~s~degradiert!',
        ['promoted1'] = 'Du hast die Person zu ~g~',
        ['promoted2'] = ' ~s~befördert!',
        ['target_promoted1'] = 'Du wurdest zum Rang ~g~',
        ['target_promoted2'] = ' ~s~befördert!',
        ['promote_error'] = '~r~Du kannst ihn nicht einen Rang geben, der höher als deiner ist!',
        ['handcuff_vehicle_error'] = '~r~Du kannst nicht fesseln, wenn du in einem Fahrzeug bist!',
        ['autopilot'] = 'Autopilot',
        ['noautopilot'] = 'Dieses Fahrzeug unterstützt kein Autopilot',
        ['cruisecontrol'] = 'Tempomat',
        ['autopilot_activated'] = 'Autopilot aktiviert',
        ['no_waypoint'] = '~r~Kein Ziel gefunden!',
        ['waypoint_reached'] = 'Du hast dein ~g~Ziel erreicht!',
        ['autopilot_deactivated'] = 'Autopilot deaktiviert',
        ['cruisecontrol_activated'] = 'Tempomat auf ~g~',
        ['cruisecontrol_activated2'] = ' kmh ~s~eingestellt',
        ['cruisecontrol_deactivated'] = 'Tempomat deaktiviert',
        ['escort'] = 'Person eskortieren',
        ['escort_error'] = '~r~Die Person muss gefesselt sein um ihn zu eskortieren!',
        ['takeoffmask'] = 'Maske abnehmen',
        ['takeoffmask_error'] = 'Die Person muss gefesselt sein, um seine Maske abnehmen zu können!',
        ['takeoffmask_sender'] = 'Du hast seine Maske ~g~abgenommen!',
        ['takeoffmask_target'] = 'Deine Maske wurde ~r~abgenommen!',
        ['headbag'] = 'Tüte über Kopf ziehen',
        ['headbag_error'] = '~r~Die Person muss gefesselt sein, um eine Tüte über sein Kopf ziehen zu können!',
        ['headbag_sender'] = 'Tüte über Kopf ziehen/vom Kopf abnehmen..',
        ['headbag_target'] = 'Dir wird eine ~r~Tüte über den Kopf ~s~gezogen..',
        ['headbag_removed'] = 'Die Tüte wurde von dein Kopf ~g~abgenommen!',
        ['job_options'] = 'Fraktion',
        ['interactions_error'] = '~r~Du bist gefesselt!',
        ['uncuff_error'] = '~r~Die Person ist nicht gefesselt',
        ['need_headbag'] = '~r~Du hast keine Kopftüte',
    },
    ['en'] = {
        ['handsup_error'] = "~r~You can't raise your hands if you're the driver.",
        ['robmenu_title'] = 'Search',
        ['robmenu_subtitle'] = 'Search Player',
        ['robmenu_idcard'] = 'View ID Card',
        ['robmenu_idcard_notify'] = 'View ID Card..',
        ['amount'] = 'Amount:',
        ['amount_desc'] = 'Enter a quantity.',
        ['ammo'] = ' bullets',
        ['playeractions_title'] = 'Interactions',
        ['playeractions_subtitle'] = 'Select a player',
        ['license_idcard'] = 'ID Card',
        ['license_driver'] = 'Drivers License',
        ['license_gun'] = 'Weapon License',
        ['player_nearby'] = 'Player',
        ['carry'] = 'Carry Player',
        ['noplayers_nearby'] = 'No players nearby!',
        ['handcuff'] = 'Ropes',
        ['handcuff_apply'] = 'Apply',
        ['handcuff_release'] = 'Release',
        ['search'] = 'Search',
        ['search_error'] = '~r~The person must raise their hands or be tied up!',
        ['putInVehicle'] = 'Put Player In Vehicle',
        ['putInVehicle_error'] = '~r~The person must be tied up!',
        ['takeFromVehicle'] = 'Take Player From Vehicle',
        ['licenses'] = 'Give License',
        ['invitejob'] = 'Invite to Job',
        ['invite_sent'] = 'You ~g~invited ~s~the person',
        ['idcard_showed'] = 'You have shown your ~g~id card',
        ['driverslicense_showed'] = 'You have shown your ~g~drivers license',
        ['gunlicense_showed'] = 'You have shown your ~g~weapon license',
        ['handcuff_error'] = 'The player must raise his hands!',
        ['no_handcuff_item'] = '~r~You have no ropes!',
        ['player_cuffed'] = "You've ~g~released ~s~the person.",
        ['player_toofar'] = 'the player is too far away.',
        ['playermenu_title'] = 'Playermenu',
        ['playermenu_subtitle'] = 'Interaction Menu',
        ['playerinteractions'] = 'Player Interactions',
        ['driver'] = 'Driver',
        ['passenger'] = 'Passenger',
        ['backleft'] = 'Back Left',
        ['backright'] = 'Back Right',
        ['trunk'] = 'Trunk',
        ['hood'] = 'Hood',
        ['vehicleinteractions'] = 'Vehicle Interactions',
        ['toggleengine'] = 'Engine',
        ['doors'] = 'Open/Close Doors',
        ['windows'] = 'Open/Close Windows',
        ['engine_on'] = 'Engine ~g~started!',
        ['engine_off'] = 'Engine ~r~stopped!',
        ['vehicle_toofar'] = '~r~the vehicle is too far away!',
        ['open'] = 'Open',
        ['close'] = 'Close',
        ['vehicle_locked'] = 'the vehicle is ~r~locked!',
        ['vehicleinteraction_locked'] = '~t~Vehicle Interactions',
        ['clothing'] = 'Clothing',
        ['on'] = 'On',
        ['off'] = 'Off',
        ['hat'] = 'Helmet/Hat',
        ['mask'] = 'Mask',
        ['glasses'] = 'Glasses',
        ['ears'] = 'Ear Accessories',
        ['chain'] = 'Chain',
        ['bag'] = 'Bag',
        ['torso'] = 'Torso',
        ['tshirt'] = 'T-Shirt',
        ['pants'] = 'Pants',
        ['shoes'] = 'Shoes',
        ['inventory'] = 'Inventory',
        ['bills'] = 'Invoices',
        ['closestatm'] = 'Closest ATM',
        ['closestgasstation'] = 'Closest Gasstation',
        ['waypoint'] = 'Set Waypoint',
        ['new_waypoint1'] = 'Waypoint set to ~g~',
        ['new_waypoint2'] = '!',
        ['waypoint_removed'] = 'You have ~r~removed ~s~the waypoint!',
        ['gps'] = 'GPS Channel',
        ['gps_code'] = 'GPS-Code',
        ['gps_code_input'] = 'Enter GPS-Code',
        ['gps_off'] = 'Deactivate GPS',
        ['gps_off_notify'] = 'You have ~r~deactivated ~s~your GPS!',
        ['no_gps_item'] = '~r~You have no GPS device!',
        ['informations'] = 'Informations',
        ['charname'] = 'First & Last Name:',
        ['birthdate'] = 'Birth Date:',
        ['job'] = 'Job:',
        ['salary'] = 'Salary:',
        ['playtime'] = 'Playtime:',
        ['channel_joined1'] = 'You have entered GPS Channel ~g~',
        ['channel_joined2'] = '',
        ['animations_title'] = 'Animations',
        ['animations_subtitle'] = 'Favorite Animations',
        ['save_anim'] = '~g~Save Animation',
        ['manage_anims'] = 'Manage Animations',
        ['save_anim_input'] = 'Save Animation',
        ['animlabel_input'] = 'Name:',
        ['animlabel_input_desc'] = 'How do you want to name the animation?',
        ['anim_input'] = 'Animation:',
        ['rename_anim'] = 'Rename',
        ['delete_anim'] = '~r~Delete',
        ['new_animlabel'] = 'New Animation Name:',
        ['anim_desc'] = 'Animation: ~b~',
        ['inventory_title'] = 'Inventory',
        ['weight'] = 'Weight: ',
        ['use'] = 'Use',
        ['give'] = 'Give',
        ['drop'] = 'Drop',
        ['use_error'] = '~r~You have no ',
        ['select_player'] = 'Select A Player',
        ['give_request1'] = 'Someone wants to give you ~g~',
        ['give_request2'] = '~s~. Press ~g~Z ~s~to take it!',
        ['item_accepted1'] = 'You have accepted ~g~',
        ['item_accepted2'] = '!',
        ['weapon_accepted1'] = 'You have accepted a ~g~',
        ['weapon_accepted2'] = '!',
        ['decline_item'] = 'You have ~r~rejected ~s~the item!',
        ['gasstation_waypoint'] = 'Waypoint set to the ~g~closest gasstation!',
        ['gasstation_error'] = '~r~no gasstation found!',
        ['atm_waypoint'] = 'Waypoint set to the ~g~closest atm!',
        ['atm_error'] = '~r~no atm found!',
        ['putInVehicle_targetnotify'] = 'You were set into the ~r~vehicle!',
        ['jobinvite_accepted'] = 'You ~g~accepted ~s~the invitation!',
        ['jobinvite_declined'] = 'You ~r~declined ~s~the invitation!',
        ['jobinvite_expired'] = 'the invitation is ~r~expired!',
        ['handcuff_applied'] = 'You have ~g~cuffed ~s~the person!',
        ['handcuff_released'] = "You've been ~g~released!",
        ['handcuff_applied_target'] = "You've been ~r~handcuffed!",
        ['anim_renamed'] = 'You renamed the animation to "~b~',
        ['anim_deleted'] = 'You ~r~deleted ~s~the animation!',
        ['channel_restricted'] = '~r~This is a protected GPS Channel',
        ['anim_saved'] = 'You ~g~saved ~s~a new animation!',
        ['target_searchidcard'] = 'Your ID Card has been ~r~taken!',
        ['target_nolonger_searching'] = 'You will no longer be searched',
        ['target_robbed_item1'] = '~r~- ',
        ['target_robbed_item2'] = '',
        ['robbed_item1'] = 'You stole a ~g~',
        ['robbed_item2'] = '!',
        ['cantcarry'] = "~r~You can't carry that much",
        ['target_robbed_gun1'] = '~r~- ',
        ['target_robbed_gun2'] = '',
        ['robbed_gun1'] = 'You stole a ~g~',
        ['robbed_gun2'] = '!',
        ['hasweapon'] = '~r~You already have this weapon!',
        ['give_request_sent'] = 'You have sent a ~g~request!',
        ['target_hasweapon'] = '~r~the person already has this weapon!',
        ['give_accepted'] = 'Your item has been ~g~accepted!',
        ['give_declined'] = 'Your item has been ~r~declined!',
        ['target_search_notify'] = 'You are being searched..',
        ['target_jobinvite1'] = 'You have been invited to the job ~g~',
        ['target_jobinvite2'] = '~s~. Press ~g~Z ~s~to accept!',
        ['sender_jobinvite_accepted'] = 'the invitation was ~g~accepted!',
        ['sender_jobinvite_declined'] = 'the invitation was ~r~declined!',
        ['jobfire'] = 'Fire',
        ['promote'] = 'Promote',
        ['degrade'] = 'Degrade',
        ['target_kicked'] = "You've been ~r~fired ~s~from your job!",
        ['kicked'] = 'You ~r~fired ~s~the person!',
        ['not_samejob'] = 'the person does not have the same job as you!',
        ['degraded1'] = 'You degraded the person to ~r~',
        ['degraded2'] = '!',
        ['target_degraded1'] = 'You have been degraded to rank ~r~',
        ['target_degraded2'] = '!',
        ['promoted1'] = 'You promoted the person to ~g~',
        ['promoted2'] = '!',
        ['target_promoted1'] = 'You have been promoted to rank ~g~',
        ['target_promoted2'] = '!',
        ['promote_error'] = "~r~You can't give him a rank higher than yours!",
        ['handcuff_vehicle_error'] = "~r~You can't tie up when you're in a vehicle!",
        ['autopilot'] = 'Autopilot',
        ['noautopilot'] = 'This vehicle does not support autopilot',
        ['cruisecontrol'] = 'Cruise Control',
        ['autopilot_activated'] = 'Autopilot enabled',
        ['no_waypoint'] = '~r~No destination found!',
        ['waypoint_reached'] = 'You have reached your ~g~destination!',
        ['autopilot_deactivated'] = 'Autopilot disabled',
        ['cruisecontrol_activated'] = 'Cruise Control set to ~g~',
        ['cruisecontrol_activated2'] = ' kmh',
        ['cruisecontrol_deactivated'] = 'Cruise Control disabled',
        ['escort'] = 'Escort Player',
        ['escort_error'] = '~r~the person must be handcuffed to escort him!',
        ['takeoffmask'] = 'Take off Mask',
        ['takeoffmask_error'] = '~r~the person must be handcuffed to remove his mask!',
        ['takeoffmask_sender'] = 'You ~g~took off ~s~his mask!',
        ['takeoffmask_target'] = 'Your mask has been ~r~took off!',
        ['headbag'] = 'Pull Headbag over',
        ['headbag_error'] = '~r~the person must be handcuffed to be able to pull a bag over his head!',
        ['headbag_sender'] = 'Pull the bag over his head/remove it from his head...',
        ['headbag_target'] = 'A bag will be ~r~pulled over your head!',
        ['headbag_removed'] = 'the bag was ~g~taken off ~s~your head!',
        ['job_options'] = 'Job',
        ['interactions_error'] = "~r~You're handcuffed!",
        ['uncuff_error'] = '~r~the person is not handcuffed',
        ['need_headbag'] = '~r~You need a headbag',
    }
}